# Generated by Django 5.0.6 on 2024-06-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(default='Egypt', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('phone', models.JSONField(blank=True, null=True)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
