# Generated by Django 5.0.6 on 2024-06-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_somerelatedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeRelatedModel',
        ),
    ]
