# Generated by Django 5.0.6 on 2024-06-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_somerelatedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
