# Generated by Django 5.0.6 on 2024-07-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
